Repository target/mmk-ui-api, pull requests merged in 2022-02, with the labels that each got.

#23 deps/swap-out-node-fetch
  backend/package.json
  backend/src/alerts/go-alert.ts
  scanner/package.json
  yarn.lock
Labels: dependencies

#24 feature(purge): purge jobs
  backend/src/jobs/index.ts
  backend/src/jobs/queues.ts
  backend/src/models/seen_strings.ts
  backend/src/services/scan.ts
  backend/src/services/seen_string.ts
  backend/src/tests/scan.service.test.ts
  backend/src/tests/seen_strings.service.test.ts
Labels: enhancement

#26 Docs
  docs/.nojekyll
  docs/README.md
  docs/index.html
Labels: documentation

#27 breakfix(scanner): fixes node-fetch dep
  scanner/package.json
  scanner/src/lib/utils.ts
  scanner/src/rules/base.ts
  scanner/src/rules/yara.ts
  yarn.lock
Labels: breakfix

#32 feat(util): strip non-ascii from scan_logs
  backend/src/lib/utils.ts
  backend/src/models/scan_logs.ts
  backend/src/tests/utils.test.ts
Labels: bug

#30 improvement(sources): resync sources on startup
  backend/src/jobs/index.ts
  backend/src/services/source.ts
  backend/src/tests/source.service.test.ts
Labels: enhancement

#31 chore(tests): handleAlert service test
  backend/src/lib/utils.ts
  backend/src/models/scan_logs.ts
  backend/src/services/scan_logs.ts
  backend/src/tests/scan_log.service.test.ts
  backend/src/tests/utils.test.ts
Labels: chore, test-coverage

#39 deps: bump
  yarn.lock
Labels: dependencies

#40 deps: upgrade vue-cli
  frontend/.eslintrc.js
  frontend/package.json
  frontend/src/components/utils/Confirm.vue
  frontend/src/views/Login.vue
  frontend/src/views/dashboard/Alerts.vue
  frontend/src/views/dashboard/AllowList.vue
  frontend/src/views/dashboard/Dashboard.vue
  frontend/src/views/dashboard/IOCs.vue
  frontend/src/views/dashboard/Scans.vue
  frontend/src/views/dashboard/Secrets.vue
  frontend/src/views/dashboard/SeenStrings.vue
  frontend/src/views/dashboard/Sites.vue
  frontend/src/views/dashboard/Sources.vue
  frontend/src/views/dashboard/Users.vue
  frontend/src/views/sites/Site.vue
  frontend/vue.config.js
  yarn.lock
Labels: dependencies
